### ISSUE TITLE
find out which markers kristina thinks are best

### ISSUE THREAD

**Issue by jovo** [neurodata/synaptome-stats#10]
to discuss, then we can try stuff again using only those

**Comment by MrAE** [comment]
email sent. awaiting reply.

**Comment by MrAE** [comment]
On Thu, Apr 14, 2016 at 3:05 AM, Kristina Micheva kmicheva@stanford.edu wrote:
I suggest: 
Synap, VGluT1, VGluT2, psd, gad, vgat, gephyr,

Or a bit bigger:
Synap, VGluT1, VGluT2, psd, gad, vgat, gephyr, VGlut3, CB1

**Comment by jovo** [comment]
i meant in report :)
sorry, i should have been more explicit.
