### ISSUE TITLE
Scatter plots of top 1%

### ISSUE THREAD

**Issue by MrAE** [neurodata/synaptome-stats#12]
Generate scatter plots with linear regression lines using data of only the top 1% of synapsin levels.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/40927432994647/168614010153020)

**Comment by jovo** [comment]
and maybe also for the top 1% of one of the strong inhibitory channels?

and let's include milestones for these issues, so we have WWW (who what
when in alignment with our parity bit).

parity bit :checkmark:

On Wed, Apr 13, 2016 at 9:54 AM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> Generate scatter plots with linear regression lines using data of only the
> top 1% of synapsin levels.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/synaptome-stats/issues/12

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by MrAE** [comment]
I picked `gad` as the inhibitory channel.  
Implemented [here](http://docs.neurodata.io/synaptome-stats/Code/MarkerExploration.html#top-1)

@jovo let me know if this is what you wanted. ??

[--- Commented from Asana.com
#commenter joshua vogelstein
---[aa]
