### ISSUE TITLE
Add co-localization to lower triangle 

### ISSUE THREAD

**Issue by MrAE** [neurodata/synaptome-stats#13]
Determine if it is possible to put the co-localization to the lower triangle of the lattice::splom plot.
Something similar to the Weiler et al paper. figure 3d ff.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/40927432994647/168613993311934)

**Comment by jovo** [comment]
i think alex and/or anish has written some co-localization stuff, so we
should talk to them.

On Wed, Apr 13, 2016 at 12:08 PM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> Determine if it is possible to put the co-localization to the lower
> triangle of the lattice::splom plot.
> Something similar to the Weiler et al paper. figure 3d ff.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/synaptome-stats/issues/13

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by MrAE** [comment]
Relocated.
