### ISSUE TITLE
y2 report

### ISSUE THREAD

**Issue by jovo** [neurodata/synaptome-stats#14]
- [x] remove gobbledygook
- [x] plot kde of log (maybe make rows = types)
- [x] for corr, make font size smaller
- [x] fix Vgl3 color
- [x] heatmap of means of log (but fixed)

**Comment by MrAE** [comment]
Note that GABABR sticks out in the clustering when the transformation is (scale º log_10 º  + 1 º Raw)

**Comment by jovo** [comment]
fig 4 of Y2 doesn't show that?

On Wed, Apr 13, 2016 at 9:20 PM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> Note that GABABR sticks out when the transformation is (scale º log_10 º +
> 1 º Raw)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/synaptome-stats/issues/14#issuecomment-209713337

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by MrAE** [comment]
It should now.

**Comment by jovo** [comment]
beautiful!
take out heatmap of log1f?
in fig 5, x axis is GABABR? or y-axis?
and can you do the ARI thingy for slogf1 for varying d, and provide
p-values?

On Wed, Apr 13, 2016 at 9:37 PM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> It should now.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/synaptome-stats/issues/14#issuecomment-209715830

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by MrAE** [comment]
I did the ARI thingy on the PCA of the Correlation matrix of slog1f for
1:elbow[2].

**Comment by MrAE** [comment]
@jovo  I need to fiddle with text sizes again. I think it's really cool though!

**Comment by jovo** [comment]
whoa, so cool!!!
can we plot something like the 2D scatter plot,
and make the symbols our cluster labels?

On Fri, Apr 15, 2016 at 7:39 PM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> @jovo https://github.com/jovo I need to fiddle with text sizes again. I
> think it's really cool though!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/synaptome-stats/issues/14#issuecomment-210685563

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by MrAE** [comment]
- [x] Add links to source code in Y2 report. 
- [x] plot p-values vs embedding dimension.

**Comment by MrAE** [comment]
I added the 2d scatter and updated font sizes.
