### ISSUE TITLE
Parity Check: Heatmaps on data not correlation matrix.

### ISSUE THREAD

**Issue by MrAE** [neurodata/synaptome-stats#16]
[Figure 4 around here](http://docs.neurodata.io/synaptome-stats/Code/Y2progress.html#k-means-level-1) is a heatmap of the per cluster means on the entire data set. 
**Not the correlation matrix.**
-  Is this correct?

**Comment by jovo** [comment]
Exactly.
Parity!

On Thursday, April 14, 2016, Jesse Leigh Patsolic notifications@github.com
wrote:

> Figure 4 around here
> http://docs.neurodata.io/synaptome-stats/Code/Y2progress.html#k-means-level-1
> is a heatmap of the per cluster means on the entire data set.
> _Not the correlation matrix._
> - Is this correct?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/synaptome-stats/issues/16

## 

the glass is all full:  half water, half air.
neurodata.io
