### ISSUE TITLE
in Y2 report

### ISSUE THREAD

**Issue by jovo** [neurodata/synaptome-stats#18]
- [ ] let's include the scatter plots of the 2 channels corresponding to the same marker
  (both synap & glu), same style as the GABABR plots.
- [x] change "raw data" to "feature vector"
- [x] "We now have the following data sets:" we actually have 4, including slogf1 and logf1

**Comment by MrAE** [comment]
Moved the first task to Y3 issue and moved to weekly-status-reports.
