### ISSUE TITLE
start Y3 report

### ISSUE THREAD

**Issue by jovo** [neurodata/synaptome-stats#19]
sections:

> always everything only on half the data
1. data
   1. which dataset
   2. definition of markers
   3. how did puncta get to us (what computer vision)
   4. definition of features (with equations)
2. feature exploration
   1. synapsin1 vs. synapsin2 in log domain and linear
   2. same for vglut1 & 2
   3. repeat the above 4 panel figure for each of the features
   4. kde plots of chosen transformation/feature pair
3. marker exploration
   1. correlation matrix
   2. 2D scatter plot colored by truth
   3. 2D scatter plot colored by truth, overlay optimal voronoi diagram (fit using linear discriminant analysis, not kmeans)
   4. same as above in 3D  
   5. ARI vs. dimension using optimal voronoi diagram
4. synapse exploration
   1. kmeans (k=2) heatmap
   2. lattice plots of GABABR (fix colors)
   3. correlation matrices for each of the 2 clusters
   4. kmeans (k=2) for level 2

**Comment by jovo** [comment]
i think this is a cool plan.
what do you think?

**Comment by MrAE** [comment]
That's a good looking outline.

**Comment by MrAE** [comment]
The skeleton is up.

**Comment by MrAE** [comment]
Moved issue to weekly-status-reports.
