### ISSUE TITLE
add yourself here

### ISSUE THREAD

**Issue by jovo** [neurodata/synaptome-stats#2]
http://docs.neurodata.io/nddocs/about/peeps.html

https://github.com/neurodata/nddocs/blob/8857ef68e4a64327e5d8ddf48d8f89d67d1ac57c/about/peeps.md

**Comment by jovo** [comment]
@gur509 you too.

**Comment by MrAE** [comment]
I do not have push access.

**Comment by jovo** [comment]
fixed
