### ISSUE TITLE
Feature Exploration:

### ISSUE THREAD

**Issue by MrAE** [neurodata/synaptome-stats#20]
- [x] Remove zeros before log scale.
- [x] create lattice plot with hex bins and regression lines for Synap and VGlut.
- [x] Add correlation and p-values.

**Comment by MrAE** [comment]
@jovo I got the first two done, [here](http://docs.neurodata.io/synaptome-stats/Code/FeatureExploration.html) but the third is harder than I thought.  Apparently ggplot doesn't seem to keep r^2 values when it does regression, so I have to do it myself for each panel.

**Comment by jovo** [comment]
so beautiful!

On Tue, May 3, 2016 at 4:35 PM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> @jovo https://github.com/jovo I got the first two done, here
> http://docs.neurodata.io/synaptome-stats/Code/FeatureExploration.html
> but the third is harder than I thought. Apparently ggplot doesn't seem to
> keep r^2 values when it does regression, so I have to do it myself for each
> panel.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/synaptome-stats/issues/20#issuecomment-216656547

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
