### ISSUE TITLE
Background research

### ISSUE THREAD

**Issue by MrAE** [neurodata/synaptome-stats#21]
- [x] How were puncta detected?
- [x] What do the features F0-F5 actually mean?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/40927432994647/168614010229191)

**Comment by MrAE** [comment]
@jovo The methods for puncta selection they used are typed out [here](https://github.com/neurodata/synaptome-stats/blob/gh-pages/Draft/background.md)

**Comment by jovo** [comment]
ok, that's a start, still missing some info. let's discuss tomorrow.

**Comment by jovo** [comment]
let's email forrest:
1. explain we found his paragraph, copy & paste into email
2. ask how puncta were detected, pointer to code would perhaps suffice
3. ask what is he thresholding, eg, mean intensity within puncta, or size of puncta?
4. we can't find a definition for computing the features in the paper, can he point us to a different place to find that info
