### ISSUE TITLE
Y2 Progress Report Token 

### ISSUE THREAD

**Issue by aksimhal** [neurodata/synaptome-stats#22]
Hello! 

For the [Y2 Progress report](https://github.com/neurodata/synaptome-stats/blob/gh-pages/Code/Y2progress.md), is the neurodata token public?  If so, where can I find it? 

Thanks!
Anish

**Comment by jovo** [comment]
kristina15

On Mon, May 16, 2016 at 2:39 PM, Anish notifications@github.com wrote:

> Hello!
> 
> For the Y2 Progress report
> https://github.com/neurodata/synaptome-stats/blob/gh-pages/Code/Y2progress.md,
> is the neurodata token public? If so, where can I find it?
> 
> Thanks!
> Anish
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/synaptome-stats/issues/22

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by MrAE** [comment]
The data used in the report is located in dropbox [here](https://www.dropbox.com/sh/u3vahw6i2blv9e3/AADROO2wHZWun1pUCeH_6e7ba?dl=0)

And the main file is `synapsinR_7thA.tif.Pivots.txt.2011Features.txt`
