### ISSUE TITLE
next steps

### ISSUE THREAD

**Issue by jovo** [neurodata/synaptome-stats#5]
on the basis of forrests last email, we now have some "ground truth", so we can explore in a slightly different fashion.  in particular, we have some "truth". so, please 
1. [x] divide the data in half by randomly selecting half, and let's explore only half
2. [x] make correlation matrix on raw, log, & rank transforms
3. [x] for each, make scree plot, select ZG[2], run pamk for 5 = 5, and compute ARI vs. marker type.
4. [x] for each, also check whether the 2 repeated markers are in the same group, hopefully, for at least one of those representations, they will be.

the point of the above is to find a good representation of the data.
the above is "group" or level-2 statistics, 
the below stuff was, in retrospect, prematurely focused on "individual" or level-1 stats, 
which will have lower power because they don't get to borrow strength across samples as much.

thank you!
- [x] plot marginals for each marker a la fig 1 for youngser
- [x] the same but not on log scale
- [ ] the same as above but z-scored (not logged)
- [ ] add figure 9 from youngser
- [ ] assuming that was on log scale, do it also on linear scale

**Comment by MrAE** [comment]
- When you say ZG[2], you mean for me to use Youngser's implementation of Zhu and Ghodsi (2006) and pick the second elbow?
- run pamk for K = 5?

**Comment by jovo** [comment]
Yup. Thanks!

On Monday, March 21, 2016, Jesse Leigh Patsolic notifications@github.com
wrote:

> - When you say ZG[2], you mean for me to use Youngser's implementation
>   of Zhu and Ghodsi (2006)?
> - run pamk for K = 5?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/synaptome-stats/issues/5#issuecomment-199453811

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by MrAE** [comment]
@jovo You mentioned that we should filter the data.  Do you have any specific directions on that?

**Comment by jovo** [comment]
discard all synapses where synapsin is < x percentile would be a start.
