### ISSUE TITLE
Progress Report for TRA

### ISSUE THREAD

**Issue by MrAE** [neurodata/synaptome-stats#9]
Dear Synaptome Consortium:

Our Synaptomes of Mouse and Man Year 2 progress report is due to NIH on May 1, 2016.  We have created a new template (based on a DARPA example) for collecting your workstream progress updates and both Ned Talley and Randy Stewart have favorably reviewed this template.  Once we receive your progress updates, we will compile into a cohesive document for review. 

Instructions:

·         Fill in the Y2 progress report template.  (I have included all workstreams in the template.  Disregard or delete workstream sections that are irrelevant for you).

·         Y2 progress report template can be found in the “Progress Reports” Folder on our Google Drive:  https://drive.google.com/open?id=0BxVJkDBA-jwPRFdVYXUySThfdGc

 o    “Synaptome Progress Report Template” document [TO BE POPULATED WITH PROGRESS]
 o    “Synaptome TRA Y2 Plan” document [FOR REFERENCE ONLY]

·         Return to me (or upload into Google drive) by Thursday 14Apr2016. 

Let me know if you have any questions.  I’m happy to have a call to discuss. Thanks in advance for your help with this activity.

My best,

Lynne

**Comment by MrAE** [comment]
@jovo --- is there anything explicit you want me to do on this?

**Comment by jovo** [comment]
just awareness for now.

On Sun, Apr 3, 2016 at 11:21 PM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> @jovo https://github.com/jovo --- is there anything explicit you want
> me to do on this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/synaptome-stats/issues/9#issuecomment-205116777

## 

the glass is all full:  half water, half air.
neurodata.io
